site:
  name: Senpai
  site: 'https://senpai.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId:
  launchDate: '02/01/2024'

# Default SEO metadata
metadata:
  title:
    default: Senpai
    template: '%s — Senpai'
  description: 'Senpai is a dating app for anime lovers. Connect and find your match today.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Senpai
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image
